FROM datajoint/djbase:py3.9-debian-8eb1715

ARG GITHUB_USERNAME=datajoint
USER anaconda:anaconda

COPY ./docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

# Install CaImAn
WORKDIR /main
RUN git clone --branch master https://github.com/kabilar/CaImAn
WORKDIR /main/CaImAn
RUN conda install -n base -c conda-forge -y mamba
RUN /bin/bash -c 'mamba env update --n base --file environment.yml'
RUN pip install .
RUN python caimanmanager.py install --inplace

# Install the workflow
WORKDIR /main/workflow-miniscope
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-lab.git
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-animal.git
RUN pip install git+https://github.com/${GITHUB_USERNAME}/element-session.git
RUN pip install --no-deps "element-interface@git+https://github.com/${GITHUB_USERNAME}/element-interface"
RUN pip install --no-deps "djarchive-client@git+https://github.com/${GITHUB_USERNAME}/djarchive-client"
RUN pip install "element-event@git+https://github.com/iamamutt/element-event.git"
RUN pip install --no-deps git+https://github.com/${GITHUB_USERNAME}/element-miniscope.git
COPY --chown=anaconda:anaconda . ./
RUN rm -f ./dj_local_conf.json
RUN pip install --no-deps .
RUN pip install -r ./requirements_test.txt
